
-- ~/.config/hypr/hyprland.lua
--
-- Personal Hyprland configuration
--
-- The bootstrap configuration generated by Hyprland is preserved at:
--   ~/.config/hypr/hyprland.lua.bootstrap

local monitors = require("monitors")
local ws = require("workspaces")
ws.init(monitors)

local scene = require("scenes").setup({monitors = monitors})
_G.scene = scene

require("programs")
require("appearance")
require("input")

require("keybinds")


require("startup")


