
wallpaper {
    monitor = DP-1
    path = ~/Pictures/Walls/astero-20190926a.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/Pictures/Walls/1046495.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/Walls/1061769.png
    fit_mode = cover
}

splash = false

